cd /d %~dp0
mkdir build\ebook
magick build\png\cover-ebook.png build\ebook\cover-ebook.jpg
magick build\png\fig-amanoiwato-ebook.png build\ebook\fig-amanoiwato-ebook.jpg
magick build\png\fig-amanoyachimata-ebook.png build\ebook\fig-amanoyachimata-ebook.jpg
magick build\png\fig-iotsuiwamura-ebook.png build\ebook\fig-iotsuiwamura-ebook.jpg
magick build\png\fig-iotsunomisumaru-ebook.png build\ebook\fig-iotsunomisumaru-ebook.jpg
magick build\png\fig-milkywayinsummer-ebook.png build\ebook\fig-milkywayinsummer-ebook.jpg
magick build\png\fig-milkywayinwinter-ebook.png build\ebook\fig-milkywayinwinter-ebook.jpg
magick build\png\fig-subaru-ebook.png build\ebook\fig-subaru-ebook.jpg
magick build\png\fig-subarunoko-ebook.png build\ebook\fig-subarunoko-ebook.jpg
magick build\png\fig-summary-haya-ebook.png build\ebook\fig-summary-haya-ebook.jpg
magick build\png\fig-summary-hi-ebook.png build\ebook\fig-summary-hi-ebook.jpg
magick build\png\fig-summary-ishi-ebook.png build\ebook\fig-summary-ishi-ebook.jpg
magick build\png\fig-summary-kushi-ebook.png build\ebook\fig-summary-kushi-ebook.jpg
magick build\png\fig-summary-mika-ebook.png build\ebook\fig-summary-mika-ebook.jpg
magick build\png\fig-summary-tama-ebook.png build\ebook\fig-summary-tama-ebook.jpg
magick build\png\photo-iwakura-ebook.png build\ebook\photo-iwakura-ebook.jpg
magick build\png\photo-magatama-ebook.png build\ebook\photo-magatama-ebook.jpg
magick build\png\photo-meteor-ebook.png build\ebook\photo-meteor-ebook.jpg
magick build\png\photo-ogame-ebook.png build\ebook\photo-ogame-ebook.jpg
magick build\png\photo-otomatsuri-ebook.png build\ebook\photo-otomatsuri-ebook.jpg
magick build\png\photo-pleiades-ebook.png build\ebook\photo-pleiades-ebook.jpg
magick build\png\photo-tategushi-ebook.png build\ebook\photo-tategushi-ebook.jpg
magick build\png\title-ebook.png build\ebook\title-ebook.jpg
