setlocal
set FROM_DIR=%USERPROFILE%\Downloads

move %FROM_DIR%\toc.html ..\docs
move %FROM_DIR%\index.html ..\docs
move %FROM_DIR%\preface.html ..\docs
move %FROM_DIR%\chapter-of-haya.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-1.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-2.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-3.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-4.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-5.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-6.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-7.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-8.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-9.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-10.html ..\docs
move %FROM_DIR%\chapter-of-haya--section-o.html ..\docs
move %FROM_DIR%\chapter-of-haya--summary.html ..\docs
move %FROM_DIR%\chapter-of-haya--supplement-1.html ..\docs
move %FROM_DIR%\chapter-of-haya--supplement-2.html ..\docs
move %FROM_DIR%\chapter-of-haya--supplement-3.html ..\docs
move %FROM_DIR%\chapter-of-haya--supplement-4.html ..\docs
move %FROM_DIR%\chapter-of-kushi.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-1.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-2.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-3.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-4.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-5.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-6.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-7.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-8.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-9.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-10.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-11.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-12.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-13.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-14.html ..\docs
move %FROM_DIR%\chapter-of-kushi--section-15.html ..\docs
move %FROM_DIR%\chapter-of-kushi--summary.html ..\docs
move %FROM_DIR%\chapter-of-kushi--supplement-1.html ..\docs
move %FROM_DIR%\chapter-of-kushi--supplement-2.html ..\docs
move %FROM_DIR%\chapter-of-kushi--supplement-3.html ..\docs
move %FROM_DIR%\chapter-of-mika.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-1.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-2.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-3.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-4.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-5.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-6.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-7.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-8.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-9.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-10.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-11.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-12.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-13.html ..\docs
move %FROM_DIR%\chapter-of-mika--section-o.html ..\docs
move %FROM_DIR%\chapter-of-mika--summary.html ..\docs
move %FROM_DIR%\chapter-of-mika--supplement-1.html ..\docs
move %FROM_DIR%\chapter-of-mika--supplement-2.html ..\docs
move %FROM_DIR%\chapter-of-tama.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-1.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-2.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-3.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-9.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-10.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-11.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-12.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-13.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-14.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-15.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-16.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-18.html ..\docs
move %FROM_DIR%\chapter-of-tama--section-o.html ..\docs
move %FROM_DIR%\chapter-of-tama--summary.html ..\docs
move %FROM_DIR%\chapter-of-tama--supplement-1.html ..\docs
move %FROM_DIR%\chapter-of-tama--supplement-2.html ..\docs
move %FROM_DIR%\chapter-of-hi.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-1.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-2.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-3.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-4.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-5.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-6.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-7.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-8.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-9.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-10.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-11.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-12.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-13.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-14.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-15.html ..\docs
move %FROM_DIR%\chapter-of-hi--section-o.html ..\docs
move %FROM_DIR%\chapter-of-hi--summary.html ..\docs
move %FROM_DIR%\chapter-of-hi--supplement-1.html ..\docs
move %FROM_DIR%\chapter-of-hi--supplement-2.html ..\docs
move %FROM_DIR%\chapter-of-hi--supplement-3.html ..\docs
move %FROM_DIR%\chapter-of-hi--supplement-4.html ..\docs
move %FROM_DIR%\chapter-of-hi--supplement-5.html ..\docs
move %FROM_DIR%\chapter-of-ishi.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-1.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-2.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-3.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-4.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-5.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-6.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-7.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-8.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-9.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-10.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-12.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-13.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-14.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-15.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-16.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-17.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-18.html ..\docs
move %FROM_DIR%\chapter-of-ishi--section-o.html ..\docs
move %FROM_DIR%\chapter-of-ishi--summary.html ..\docs
move %FROM_DIR%\chapter-of-ishi--supplement-1.html ..\docs
move %FROM_DIR%\chapter-of-ishi--supplement-2.html ..\docs
move %FROM_DIR%\chapter-of-ishi--supplement-3.html ..\docs
move %FROM_DIR%\chapter-of-ishi--supplement-4.html ..\docs
move %FROM_DIR%\appendix.html ..\docs
move %FROM_DIR%\revision-history.html ..\docs
pause
